name: Pool Info Import

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow every day at 0 hr 0 mins.
  schedule:
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install the packages
        run: npm --prefix ./src install
      - name: Run data import script
        run: POOLID=${{ secrets.POOLID }} BASEURL=${{ secrets.BASE_URL }}  PROJECT_ID=${{ secrets.PROJECT_ID }} MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE}}  MYSQL_HOSTNAME=${{ secrets.MYSQL_HOSTNAME}} node ./src/fetch_data.js
